### ISSUE TITLE
UserRoles not rendering

### ISSUE THREAD

**Issue by zulfikarvohra** [TypecastException/AspNetExtendingIdentityRoles#1]
UserRoles view does not showing editable roles.

**Comment by xivSolutions** [comment]
Not sure I'm seeing what you are seeing? UserRoles allows selection of roles for a specific user via checkboxes. To edit roles, go to Roles, then click Edit link. 

Can you give a littel more detail, and/or maybe post a screenshot?

**Comment by zulfikarvohra** [comment]
Sorry xivsolutions...
I resolved the problem...i didn't added view template in my View/Shared Directory.
Thanks & Keep doing Awesome work...

**Comment by xivSolutions** [comment]
Good deal! Thanks for reading :)
